[pytest]
addopts = -s --alluredir ../../report --clean-alluredir
testpaths = ./scripts
python_files = test_*.py
python_calsses = Test*
python_functions = test_*











































































































































































































































































