from selenium.webdriver.common.by import By

pur_input = By.XPATH, "//*[@id='app']/div/div[4]/div/div/div[1]/input"
pur_search = By.XPATH, "//*[@id='app']/div/div[4]/div/div/div[1]/div/div/i"
pur_chose = By.XPATH, "//*[@id='app']/div/div[3]/div[2]/div/div[2]/div[1]"
pur_Purple = By.XPATH, "//*[@id='app']/div/div[4]/div/div[2]/div[4]/div[2]/div[2]"
pur_onetb = By.XPATH, "//*[@id='app']/div/div[4]/div/div[2]/div[5]/div[2]/div[4]/div"
pur_go_purchase = By.XPATH, "//*[@id='app']/div/div[4]/div/div[2]/div[6]/div[3]/button[1]"
pur_Checkout = By.XPATH, "//*[@id='app']/div/div[3]/div/div[2]/div[2]/a[2]/button"
pur_go_Checkout = By.XPATH, "//*[@id='app']/div/div[4]/div[2]/div[3]/div[2]/div[4]"
pur_orders = By.XPATH, "//*[@id='app']/div/div[5]/div[1]"
pur_alipay = By.XPATH, "//*[@id='app']/div/div[3]/div[1]/span"
pur_pay_ok = By.XPATH, "//*[@id='app']/div/div[3]/div[3]/div/button[2]"
pur_check_orders = By.XPATH, "//*[@id='app']/div/div[3]/button[2]"
pur_get_info = By.XPATH, "//*[@id='app']/div/div[2]/div/div[2]/div/div/div[3]/div[1]/div[2]/div[1]/div/div/div[1]"
pur_cancel_ordres = By.XPATH, "//*[@id='app']/div/div[2]/div/div[2]/div/div/div[3]/div[1]/div[2]/div[3]/button[2]"
pur_cancel_ok = By.XPATH, "//*[text()='确定']"
pur_get_status = By.XPATH, "//*[@id='app']/div/div[2]/div/div[2]/div/div/div[3]/div[1]/div[1]/div[1]/div[1]"
